File: .github\dependabot.yml
````````
# FixItFred: Sprint 91.23.E – Created valid NuGet-only configuration for .NET project, removed unsupported npm config
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
