name: "NuGet Dependency Submission"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1' # Every Monday at 3 AM UTC

permissions:
  contents: read
  security-events: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x' # Ensure this matches your project

      - name: Restore dependencies
        run: dotnet restore

      - name: Submit NuGet dependencies
        uses: github/submit-nuget-dependencies@v1
        with:
          dotnet-project-path: MVP-Core.csproj

